### ISSUE TITLE
proposal - additional promisify.object modes

### ISSUE THREAD

**Issue by Gvozd** [dpw/promisify#2]
second argument - object constuctor(instead simple object)

for example `request` module has a root function like object
now, if I use promisify.object - I miss base function
I'd like write something like this
```js
promisify.object({
  get: promisify.cb_func()
}, function(curObj) {
 return promisify.cb_func()(curObj);
});
```

If yout think that good idea - i may do PullRequest

**Comment by dpw** [comment]
It seems like a good idea.

Though I may be missing something: in the example you show, couldn't you just write:

```
promisify.object({
  get: promisify.cb_func()
}, promisify.cb_func());
```

?

**Comment by Gvozd** [comment]
yes, you right
please merge PR
